// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace Workshop_API.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241007194434_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Conseil", b =>
                {
                    b.Property<int?>("ConseilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ConseilId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProduitId")
                        .HasColumnType("int");

                    b.HasKey("ConseilId");

                    b.HasIndex("ProduitId");

                    b.ToTable("Conseil");
                });

            modelBuilder.Entity("api.Models.Produit", b =>
                {
                    b.Property<int?>("ProduitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ProduitId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProduitId");

                    b.ToTable("Produit");
                });

            modelBuilder.Entity("api.Models.Conseil", b =>
                {
                    b.HasOne("api.Models.Produit", "Produit")
                        .WithMany("Conseils")
                        .HasForeignKey("ProduitId");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("api.Models.Produit", b =>
                {
                    b.Navigation("Conseils");
                });
#pragma warning restore 612, 618
        }
    }
}
