// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace Workshop_API.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Advice", b =>
                {
                    b.Property<int>("AdviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdviceId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FlagIsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdviceId");

                    b.ToTable("Advice");

                    b.HasData(
                        new
                        {
                            AdviceId = 1,
                            Content = "Pendant les repas",
                            DateStart = new DateTime(2024, 10, 9, 10, 11, 24, 552, DateTimeKind.Local).AddTicks(6812),
                            FlagIsDeleted = false,
                            Type = "Posologie"
                        },
                        new
                        {
                            AdviceId = 2,
                            Content = "Se rincer la bouche après utilisation",
                            DateStart = new DateTime(2024, 10, 9, 10, 11, 24, 552, DateTimeKind.Local).AddTicks(6818),
                            FlagIsDeleted = false,
                            Type = "Précaution"
                        },
                        new
                        {
                            AdviceId = 3,
                            Content = "Pas d'activité physique intense",
                            DateStart = new DateTime(2024, 10, 9, 10, 11, 24, 552, DateTimeKind.Local).AddTicks(6823),
                            FlagIsDeleted = false,
                            Type = "Précaution"
                        },
                        new
                        {
                            AdviceId = 4,
                            Content = "Uniquement le matin",
                            DateStart = new DateTime(2024, 10, 9, 10, 11, 24, 552, DateTimeKind.Local).AddTicks(6828),
                            FlagIsDeleted = false,
                            Type = "Précaution"
                        },
                        new
                        {
                            AdviceId = 5,
                            Content = "4/jour max, 1 toutes les 6h",
                            DateStart = new DateTime(2024, 10, 9, 10, 11, 24, 552, DateTimeKind.Local).AddTicks(6833),
                            FlagIsDeleted = false,
                            Type = "Précaution"
                        });
                });

            modelBuilder.Entity("api.Models.Pharmacy", b =>
                {
                    b.Property<int>("PharmacyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PharmacyId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PharmacyId");

                    b.ToTable("Pharmacy");

                    b.HasData(
                        new
                        {
                            PharmacyId = 1,
                            Name = "Pharmacie de l'Eurotéléport"
                        },
                        new
                        {
                            PharmacyId = 2,
                            Name = "Pharmacie de la Mitterie"
                        },
                        new
                        {
                            PharmacyId = 3,
                            Name = "Pharmacie de la Vigne"
                        },
                        new
                        {
                            PharmacyId = 4,
                            Name = "Pharmacie Art Nouveau"
                        });
                });

            modelBuilder.Entity("api.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("PharmacyId");

                    b.ToTable("Prescription");

                    b.HasData(
                        new
                        {
                            PrescriptionId = 1,
                            Date = new DateTime(2024, 10, 9, 10, 11, 24, 552, DateTimeKind.Local).AddTicks(6893),
                            PharmacyId = 1
                        },
                        new
                        {
                            PrescriptionId = 2,
                            Date = new DateTime(2024, 10, 9, 10, 11, 24, 552, DateTimeKind.Local).AddTicks(6897),
                            PharmacyId = 2
                        },
                        new
                        {
                            PrescriptionId = 3,
                            Date = new DateTime(2024, 10, 9, 10, 11, 24, 552, DateTimeKind.Local).AddTicks(6900),
                            PharmacyId = 1
                        });
                });

            modelBuilder.Entity("api.Models.PrescriptionProduct", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("PrescriptionId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("PrescriptionProducts");

                    b.HasData(
                        new
                        {
                            PrescriptionId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            PrescriptionId = 1,
                            ProductId = 4
                        });
                });

            modelBuilder.Entity("api.Models.PrescriptionProductAdvice", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("AdviceId")
                        .HasColumnType("int");

                    b.HasKey("PrescriptionId", "ProductId", "AdviceId");

                    b.HasIndex("AdviceId");

                    b.ToTable("PrescriptionProductAdvice");

                    b.HasData(
                        new
                        {
                            PrescriptionId = 1,
                            ProductId = 1,
                            AdviceId = 5
                        },
                        new
                        {
                            PrescriptionId = 1,
                            ProductId = 4,
                            AdviceId = 4
                        },
                        new
                        {
                            PrescriptionId = 1,
                            ProductId = 4,
                            AdviceId = 1
                        });
                });

            modelBuilder.Entity("api.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CIP")
                        .HasColumnType("int");

                    b.Property<string>("DCI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FlagIsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CIP = 1234567,
                            DCI = "Paracetamol",
                            Dosage = "500mg",
                            FlagIsDelete = false,
                            Name = "Doliprane"
                        },
                        new
                        {
                            ProductId = 2,
                            CIP = 2345678,
                            DCI = "Ibuprofen",
                            Dosage = "400mg",
                            FlagIsDelete = false,
                            Name = "Advil"
                        },
                        new
                        {
                            ProductId = 3,
                            CIP = 2345679,
                            DCI = "Propionate de fluticasone",
                            Dosage = "250µg",
                            FlagIsDelete = false,
                            Name = "Flixotide"
                        },
                        new
                        {
                            ProductId = 4,
                            CIP = 2345677,
                            DCI = "Prednisolone",
                            Dosage = "20mg",
                            FlagIsDelete = false,
                            Name = "Solupred"
                        },
                        new
                        {
                            ProductId = 5,
                            CIP = 2345677,
                            DCI = "Lévofloxaxine ",
                            Dosage = "500mg",
                            FlagIsDelete = false,
                            Name = "Tavanic"
                        });
                });

            modelBuilder.Entity("api.Models.ProductAdvice", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("AdviceId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "AdviceId");

                    b.HasIndex("AdviceId");

                    b.ToTable("ProductAdvice");

                    b.HasData(
                        new
                        {
                            ProductId = 4,
                            AdviceId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            AdviceId = 4
                        },
                        new
                        {
                            ProductId = 1,
                            AdviceId = 5
                        });
                });

            modelBuilder.Entity("api.Models.Prescription", b =>
                {
                    b.HasOne("api.Models.Pharmacy", "Pharmacy")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("api.Models.PrescriptionProduct", b =>
                {
                    b.HasOne("api.Models.Prescription", "Prescription")
                        .WithMany("PrescriptionProducts")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Product", "Product")
                        .WithMany("PrescriptionProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prescription");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("api.Models.PrescriptionProductAdvice", b =>
                {
                    b.HasOne("api.Models.Advice", "Advice")
                        .WithMany("PrescriptionProductAdvices")
                        .HasForeignKey("AdviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("api.Models.PrescriptionProduct", "PrescriptionProduct")
                        .WithMany("PrescriptionProductAdvices")
                        .HasForeignKey("PrescriptionId", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advice");

                    b.Navigation("PrescriptionProduct");
                });

            modelBuilder.Entity("api.Models.ProductAdvice", b =>
                {
                    b.HasOne("api.Models.Advice", "Advice")
                        .WithMany("ProductAdvices")
                        .HasForeignKey("AdviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Product", "Product")
                        .WithMany("ProductAdvices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("api.Models.Advice", b =>
                {
                    b.Navigation("PrescriptionProductAdvices");

                    b.Navigation("ProductAdvices");
                });

            modelBuilder.Entity("api.Models.Pharmacy", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("api.Models.Prescription", b =>
                {
                    b.Navigation("PrescriptionProducts");
                });

            modelBuilder.Entity("api.Models.PrescriptionProduct", b =>
                {
                    b.Navigation("PrescriptionProductAdvices");
                });

            modelBuilder.Entity("api.Models.Product", b =>
                {
                    b.Navigation("PrescriptionProducts");

                    b.Navigation("ProductAdvices");
                });
#pragma warning restore 612, 618
        }
    }
}
